/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "BridgeEvent"): TruffleContracts.BridgeEventContract;
      require(name: "BridgeEvent"): TruffleContracts.BridgeEventContract;
      require(name: "ConvertLib"): TruffleContracts.ConvertLibContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "MetaCoin"): TruffleContracts.MetaCoinContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
    }
  }
}
